#! /bin/bash

echo "checking ALL"

dirs=`ls -d */`

# do git-diff on all...
for dir in $dirs
do
    if test -e $dir/.git
    then
	pushd $dir > /dev/null
	git diff-index --exit-code --quiet HEAD
	if [ $? -ne 0 ];
	then
	  echo "$dir needs git action"
	fi
	popd > /dev/null
    fi
done
echo "Done"
