#! /bin/bash

echo "checking ALL"

dirs=`ls -d */`

delete=(json Glem libexttextcat tinyxml2) # not my problem!

for del in ${delete[@]}
do
   dirs=("${dirs[@]/$del}")
done

# do git-diff on all...
for dir in $dirs
do
    if test -e $dir/.git
    then
	pushd $dir > /dev/null
	branch=`git branch | grep \* | cut -d ' ' -f2`
	git diff --quiet HEAD
	if [ $? -ne 0 ];
	then
	    echo "$dir [$branch] needs git action"
	else
	    git push --dry-run --quiet
	    if [ $? -ne 0 ];
	    then
		echo "$dir [$branch] needs git push"
	    else
		if [ $branch != "master" ] && [ $branch != "main" ];
		then
		    echo $dir "[$branch]     OK"
		fi
	    fi
	fi
	popd > /dev/null
    fi
done
echo "Done"
