#! /bin/bash

echo "Updating ALL"
wd=`pwd`
prefix="${wd}/../usr/local/"

dirs=`ls -d */`

# configure and make all
for dir in $dirs
do
    app=${dir%/}
    if [ -e $app/.git ]
    then
	rm $app.log > /dev/null 2>&1
	pushd $app > /dev/null 2>&1
	git pull  > /dev/null 2>&1
	echo "building in $app"
	if [ -e Makefile ]
	then
	    make install > ../$app.log 2>&1
	    if [ $? -ne 0 ]
	    then
		echo "$app failed: see $app.log"
	    else
		rm ../$app.log
	    fi
	else
	    echo "No Makefile in $dir"
	fi
	popd  > /dev/null 2>&1
    else
	echo "skipping $app, not a git repository"
    fi
done
