#! /bin/bash

echo "Updating ALL"
wd=`pwd`
prefix="${wd}/../usr/local/"

dirs=`ls -d */`

# configure and make all
for app in $dirs
do
    if [ -e $app/.git ]
    then
	pushd $app
	if [ -e Makefile ]
	then
	    make install
	else
	    echo "No Makefile in $dir"
	fi
	git pull
	popd
    else
	echo "skipping $app, not a git repository"
    fi
done
